window.ORGANIC_CONFIG = {
  "version": 9,
  "seed": 2772206847,
  "previewDurationSeconds": 10,
  "previewLoop": false,
  "maxDpr": 1.85,
  "centerXDesktop": 0.235,
  "centerXMobile": 0.5,
  "centerYDesktop": 0.5,
  "centerYMobile": 0.44,
  "heightDesktop": 0.96,
  "heightMobile": 0.86,
  "scrollSmoothing": 0.065,
  "pointerSmoothing": 0.045,
  "strandIdleTurnsPerMinute": 0.11,
  "strandScrollTurns": 0.46,
  "orbitalTurnsPerMinute": 0.42,
  "strandCountDesktop": 43,
  "strandCountMobile": 38,
  "strandStepsDesktop": 75,
  "strandStepsMobile": 78,
  "initialRootStage": 0.02,
  "growthLayers": [
    {
      "path": "assets/stage-03-bud.webp",
      "start": 0.16,
      "peak": 0.3,
      "end": 0.475,
      "opacity": 0.1,
      "scale": 1,
      "yOffset": 0,
      "drift": 1.5,
      "kind": "bud"
    },
    {
      "path": "assets/stage-05-petals.webp",
      "start": 0.31,
      "peak": 0.48,
      "end": 0.66,
      "opacity": 0.11,
      "scale": 1,
      "yOffset": 0,
      "drift": 1.5,
      "kind": "petals"
    },
    {
      "path": "assets/stage-07-bloom.webp",
      "start": 0.49,
      "peak": 0.66,
      "end": 0.85,
      "opacity": 0.12,
      "scale": 1,
      "yOffset": 0,
      "drift": 1.5,
      "kind": "bloom"
    },
    {
      "path": "assets/stage-09-mature.webp",
      "start": 0.6,
      "peak": 0.82,
      "end": 0.985,
      "opacity": 0.48,
      "scale": 1.095,
      "yOffset": 0,
      "drift": 2,
      "kind": "mature"
    }
  ],
  "finalTexturePath": "assets/final-frame.webp",
  "finalTextureStart": 0.535,
  "finalTextureFull": 1,
  "finalTextureScale": 1.095,
  "finalTextureYOffset": -0.035,
  "finalTextureBreathing": 0.02,
  "finalBaseAlpha": 0,
  "finalFrontAlpha": 0.82,
  "finalBackLowerAlpha": 0.35,
  "finalBackMiddleAlpha": 0.37,
  "finalBackUpperAlpha": 0.42,
  "accentStrandAlpha": 0.47,
  "accentOrbitalAlpha": 1.04,
  "showGrowthLayers": true,
  "showRoots": true,
  "showStrands": true,
  "showPetals": true,
  "showPod": true,
  "showClusters": true,
  "showOrbits": true,
  "showFinalTexture": true,
  "rootAlpha": 0,
  "orbitBackAlpha": 0.53,
  "strandBackAlpha": 0.7,
  "petalBackAlpha": 1.03,
  "podAlpha": 0.37,
  "clusterAlpha": 0.93,
  "strandFrontBaseAlpha": 0.69,
  "petalFrontBaseAlpha": 0.19,
  "orbitFrontBaseAlpha": 0.18
};
